throttle: more redis limit tweaks
trying to hone in on this, which I think is an edge case when we try to
acquire just as element(s) are expiring and producing an empty set:

```
thread 'limit::test::test_redis' panicked at crates/throttle/src/limit.rs:469:14:
called `Result::unwrap()` on an `Err` value: AnyHow(error invoking redis
lease acquisition script
key=test_redis-4e24b3a0-81f8-4cbe-abfb-16c63ee3e7cf now=1736174679.13151
expires=1736174681.13151 limit=2
uuid=346b46d2-00d6-4109-9775-a7559d484eba

Caused by:
    An error was signalled by the server - ResponseError: Error running
    script (call to f_2e0bdd7bbe1fa07f6cc6eebfba9ef415044c97a5):
    @user_script:13: ERR value is not an integer or out of range)
```