fix shutdown deadlock if multiple things call request_shutdown
The issue in my case was:

```
2023-03-20T21:38:56.945962Z ERROR localset-0 kumod::mod_kumo: Error in spool: Opening spool data: Corruption: While creating a new Db, wal_dir contains existing log file: : 000004.log
Shutdown requested, please wait while work is saved
Shutdown completed OK!
2023-03-20T21:38:56.966846Z ERROR localset-0 kumod::mod_kumo: Error in spool: Opening spool meta: Corruption: While creating a new Db, wal_dir contains existing log file: : 000004.log
2023-03-20T21:38:57.025241Z ERROR localset-0 kumod: problem initializing: No spools have been defined
smtp listener on 0.0.0.0:25 -> stopping
Error: Initialization raised an error
smtp listener on [::]:25 -> stopping
```